esphome:
  name: controlpad2
  friendly_name: ControlPad2

esp32:
  board: esp32-s2-saola-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "FYaG0+DJO9rJaQOu7bJyjQT0Jpvoz5ws2u+Z/V0jZZs="

ota:
  - platform: esphome
    password: "7e8d125e2b9de0759ffb5e9158697196"

wifi:
  ssid: !secret wifi_ssid_m
  password: !secret wifi_password_m

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Controlpad2 Fallback Hotspot"
    password: "BriUVetpsnHe"

    

globals:
  - id: page_active
    type: int
    initial_value: '0'

i2c:
  sda: GPIO18
  scl: GPIO36
  frequency: 100kHz
  scan: true

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO8
      mode: INPUT_PULLUP
      inverted: true
    name: "Button1"
    on_press:
      - display.page.show: page1
      - lambda: |-
          id(page_active) = 1;  

  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: true
    name: "Button2"
    on_press:
      - display.page.show: page2
      - lambda: |-
          id(page_active) = 2;
  
  - platform: gpio
    pin:
      number: GPIO21
      mode: INPUT_PULLUP
      inverted: true
    name: "toggle1"
    on_press:
      then:
      - if:
          condition:
            lambda: |-
              return id(page_active) == 1;
          then:
            - homeassistant.service:
                service: light.toggle
                data:
                  entity_id: light.led_controller_1_light_bar

sensor:
  - platform: homeassistant
    name: "Bar Light Brightness"
    id: led_controller_1_light_bar_brightness
    entity_id: light.led_controller_1_light_bar
    attribute: brightness
    unit_of_measurement: "%"
    filters:
      - lambda: |-
          if (isnan(x)) return 0.0f;
          return int(x * 100.0f / 255.0f);

  - platform: rotary_encoder
    name: "Encoder 1"
    id: encoder1
    pin_a: GPIO10
    pin_b: GPIO11
    resolution: 4
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Encoder1 value: %.0f"
            args: ["id(encoder1).state"]

  - platform: rotary_encoder
    name: "Encoder 2"
    id: encoder2
    pin_a: GPIO15
    pin_b: GPIO16
    resolution: 4
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Encoder2 value: %.0f"
            args: ["id(encoder2).state"]

  - platform: rotary_encoder
    name: "Encoder 3"
    id: encoder3
    pin_a: GPIO33
    pin_b: GPIO34
    resolution: 4
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Encoder3 value: %.0f"
            args: ["id(encoder3).state"]

  - platform: rotary_encoder
    name: "Encoder 4"
    id: encoder4
    pin_a: GPIO38
    pin_b: GPIO39
    resolution: 4
    on_value:
      then:
        - logger.log:
            level: INFO
            format: "Encoder4 value: %.0f"
            args: ["id(encoder4).state"]

# SH1106 128×64 over I2C
display:
  - platform: ssd1306_i2c
    model: SH1106 128x64
    id: display1

    address: 0x3D
    rotation: 0
    update_interval: 1000ms
    pages:
      - id: page1
        lambda: |-
          int val1 = int((id(led_controller_1_light_bar_brightness).state / 100.0f) * 31);
          if (val1 != 0) {
            val1 += 1;
          }
          it.filled_rectangle(10, 64-val1, 5, 33);

          // it.printf(0, 0, id(font1), "%.0f%%", id(led_controller_1_light_bar_brightness).state);
      - id: page2
        lambda: |-
          it.print(0, 10, id(font1), "This is page 2!");
          it.filled_rectangle(10, 20, 80, 5);

font:
  - file: "gfonts://Ubuntu"
    id: font1
    size: 20

# captive_portal:
captive_portal:
